---
title: "H20"
author: "Steven Futter"
date: "2/28/2017"
output: html_document
---

http://h2o-release.s3.amazonaws.com/h2o/rel-tverberg/5/index.html

```{r}
# The following two commands remove any previously installed H2O packages for R.
if ("package:h2o" %in% search()) { detach("package:h2o", unload=TRUE) }
if ("h2o" %in% rownames(installed.packages())) { remove.packages("h2o") }

# Next, we download packages that H2O depends on.
if (! ("methods" %in% rownames(installed.packages()))) { install.packages("methods") }
if (! ("statmod" %in% rownames(installed.packages()))) { install.packages("statmod") }
if (! ("stats" %in% rownames(installed.packages()))) { install.packages("stats") }
if (! ("graphics" %in% rownames(installed.packages()))) { install.packages("graphics") }
if (! ("RCurl" %in% rownames(installed.packages()))) { install.packages("RCurl") }
if (! ("jsonlite" %in% rownames(installed.packages()))) { install.packages("jsonlite") }
if (! ("tools" %in% rownames(installed.packages()))) { install.packages("tools") }
if (! ("utils" %in% rownames(installed.packages()))) { install.packages("utils") }

# Now we download, install and initialize the H2O package for R.
install.packages("h2o", type="source", repos=(c("http://h2o-release.s3.amazonaws.com/h2o/rel-tverberg/5/R")))
library(h2o)
localH2O = h2o.init(nthreads=-1)

# Finally, let's run a demo to see H2O at work.
demo(h2o.kmeans)
```

Let's now look at the deep learning algorithm in R using H2O
```{r}
library(h2o)
h2o.init()
prosPath = system.file("extdata", "prostate.csv", package = "h2o")
prostate.hex = h2o.importFile(path = prosPath)

head(prostate.hex)

prostate.dl = h2o.deeplearning(x = 3:9, y = 2, training_frame = prostate.hex,hidden = c(100, 200), epochs = 5)
prostate.deepfeatures_layer1 = h2o.deepfeatures(prostate.dl, prostate.hex, layer = 1)
prostate.deepfeatures_layer2 = h2o.deepfeatures(prostate.dl, prostate.hex, layer = 2)
head(prostate.deepfeatures_layer1)
head(prostate.deepfeatures_layer2)
```



```{r}
library(h2o)
h2o.init()
iris.hex <- as.h2o(iris)
iris.dl <- h2o.deeplearning(x = 1:4, y = 5, training_frame = iris.hex)
# now make a prediction
predictions <- h2o.predict(iris.dl, iris.hex)
predictions
```

ADZUNA EXAMPLE OF REGRESSION PROBLEM
```{r}
adzuna.train = read.csv('~/Dropbox/NU/ADVANCED_MODELING/ADZUNA/datasets/train_add_tfidf_keywordfreq_jun_long.csv',fileEncoding = "latin1", nrow=5000)
head(adzuna.train)
names(adzuna.train)

str(adzuna.train)

library(h2o)
h2o.init()
adzuna.train.hex <- as.h2o(adzuna.train)

# need to break out the categories into binary values here:



# need to run the neural network with half the number of hidden nodes: 
adzuna.train.dl <- h2o.deeplearning(x = 10:20, y = 1, training_frame = adzuna.train.hex, hidden=c(5))


# make a prediction here
predictions <- h2o.predict(adzuna.train.dl, adzuna.train.hex)
predictions


# evaluate the quality of prediction here
adzuna.train.mse = mean((predictions-adzuna.train.hex$SALARYNORM)^2) 
adzuna.train.mse

```

```{r}
adzuna.train = read.csv('~/Dropbox/NU/ADVANCED_MODELING/ADZUNA/datasets/train_add_tfidf_keywordfreq_jun_long.csv',fileEncoding = "latin1", nrow=500)
attach(adzuna.train)
names(adzuna.train)
# I use a trick here to break out the categorical variables into binary 1/0 values
adzunaMatrix = data.frame(model.matrix(SALARYNORM~., adzuna.train))

# add back the log.price variable
adzunaMatrix = cbind(SALARYNORM,adzunaMatrix)
adzuna = adzunaMatrix

# let's also remove price so that there is no confusion as to which response variable should be used
#dropIdx = which(names(adzuna) %in% c("Id","SalaryNormalized","X.Intercept.","X"))
dropIdx = which(names(adzuna) %in% c("X.Intercept.","X","Id"))
adzuna = adzuna[,-dropIdx]

names(adzuna)
head(adzuna,2)

str(adzuna)
```



```{r}

adzuna.train = adzuna

library(h2o)
h2o.init()
adzuna.train.hex <- as.h2o(adzuna.train)
dim(adzuna.train.hex)

adzuna.train.hex = adzuna.train.hex[2:501,]
head(adzuna.train.hex)
dim(adzuna.train.hex)

# need to break out the categories into binary values here:
# DID THIS IN SECTION ABOVE ALREADY.
dim(adzuna.train.hex) # 815 columns so i choose 400 nodes.
head(adzuna.train.hex)


# need to run the neural network with half the number of hidden nodes: 
adzuna.train.dl <- h2o.deeplearning(x = 2:815, y = 1, training_frame = adzuna.train.hex, hidden=c(400))


# make a prediction here
predictions <- h2o.predict(adzuna.train.dl, adzuna.train.hex)
predictions

length(adzuna.train.hex$SALARYNORM)

# evaluate the quality of prediction here
adzuna.train.mse = mean((predictions-adzuna.train.hex$SALARYNORM)^2) 
adzuna.train.mse

```




